services:
  bot:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      redis:
        condition: service_healthy
    networks:
        - main

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - main
    
volumes:
  redisdata:

networks:
  main:
    driver: bridge
