name: Deploy to production

on:
  push:
    branches:
      - main     # или любая ветка, от которой вы деплоите

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем ваш репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настраиваем SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      # 4. Подключаемся к серверу и запускаем команды деплоя
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
       
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 777
          script: |
            cd /home/admin/telegram_bot
            git pull origin main
            docker compose build --no-cache
            docker compose up -d --remove-orphans
